foodbank/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'foodbank'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('sign_up/', views.sign_up_view, name='sign_up'),
    path('staff_sign_up/', views.staff_sign_up, name='staff_sign_up'),
    path('staff_login/', views.staff_login_view, name='staff_login'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('main_page/', views.main_page_view, name='main_page'),
    path('volunteers/', views.VolunteerView.as_view(), name='volunteers'),
    path('foodbanks/', views.FoodBankView.as_view(), name='foodbanks'),
    path('tasks/', views.TaskView.as_view(), name='tasks'),
    path('volunteer_tasks/', views.volunteer_task_view, name='volunteer_tasks'),
    path('volunteer_tasks/delete/', views.volunteer_task_delete, name='volunteer_task_delete'),
    path('vehicles/', views.VehicleView.as_view(), name='vehicles'),
    path('transits/', views.TransitView.as_view(), name='transits'),
    path('fooditems/', views.fooditem_view, name='fooditems'),
    path('fooditems/delete/', views.fooditem_delete, name='fooditem_delete'),
    path('recipient_organizations/', views.recipient_organization_view, name='recipient_organizations'),
    path('recipient_organizations/delete/', views.recipient_organization_delete, name='recipient_organization_delete'),
    path('distributed-food-items/', views.distributed_food_item_view, name='distributed_food_items'),
    path('distributed-food-items/delete/', views.distributed_food_item_delete, name='distributed_food_item_delete'),
    path('donators/', views.donator_view, name='donators'),
    path('donators/delete/', views.donator_delete, name='donator_delete'),
    path('foodgroups/', views.foodgroup_view, name='foodgroups'),
    path('foodgroups/delete/', views.foodgroup_delete, name='foodgroup_delete'),
    path('setup_db/', views.setup_database, name='setup_db')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('foodbank.urls')),
]

foodbank/models.py
from django.db import models
from datetime import datetime

class Volunteer(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    street_address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    home_state = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=20)
    email = models.CharField(max_length=100)

class FoodBank(models.Model):
    id = models.AutoField(primary_key=True)
    street_address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    home_state = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=20, default="00000")
    manager = models.ForeignKey(Volunteer, on_delete=models.PROTECT, null=True, blank=True)
    phone_number = models.CharField(max_length=20)
    email = models.CharField(max_length=100)

class Task(models.Model):
    id = models.AutoField(primary_key=True)
    description = models.CharField(max_length=255)
    start_date_time = models.DateTimeField(default=datetime.strptime('2000-01-01 09:00:00', "%Y-%m-%d %H:%M:%S"))
    end_date_time = models.DateTimeField(default=datetime.strptime('2000-01-01 12:00:00', "%Y-%m-%d %H:%M:%S"))
    associated_food_bank = models.ForeignKey(FoodBank, on_delete=models.CASCADE, null=True, blank=True)
    min_volunteers = models.IntegerField(default=0)
    max_volunteers = models.IntegerField(default=10)

class Volunteer_Task(models.Model):
    id = models.AutoField(primary_key=True)
    volunteer = models.ForeignKey(Volunteer, on_delete=models.CASCADE, null=True, blank=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, null=True, blank=True)

class Vehicle(models.Model):
    id = models.AutoField(primary_key=True)
    driver_volunteer = models.ForeignKey(Volunteer, on_delete=models.CASCADE, null=True, blank=True)
    vehicle_type = models.CharField(max_length=255, default="")
    total_passenger_capacity = models.IntegerField(default=0)

class TransitSchedule(models.Model):
    id = models.AutoField(primary_key=True)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, null=True, blank=True)
    arrival_date_time = models.DateTimeField(default=datetime.strptime('2000-01-01 09:00:00', "%Y-%m-%d %H:%M:%S"))
    departure_date_time = models.DateTimeField(default=datetime.strptime('2000-01-01 12:00:00', "%Y-%m-%d %H:%M:%S"))
    current_available_capacity = models.IntegerField(default=0)

class Donator(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=20)
    email = models.CharField(max_length=100)

class FoodGroup(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    
class FoodItem(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    food_group = models.ForeignKey(FoodGroup, on_delete=models.CASCADE)
    expiration_date = models.DateField()
    item_size = models.CharField(max_length=255)
    associated_food_bank = models.ForeignKey(FoodBank, on_delete=models.CASCADE, null=True, blank=True)
    donator = models.ForeignKey(Donator, on_delete=models.CASCADE, null=True, blank=True)


class DistributedFoodItem(models.Model):
    id = models.AutoField(primary_key=True)
    food_item = models.ForeignKey(FoodItem, on_delete=models.CASCADE, null=True, blank=True)
    recipient_org = models.ForeignKey('RecipientOrganization', on_delete=models.CASCADE, null=True, blank=True)

class RecipientOrganization(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    street_address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    home_state = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=20)
    email = models.CharField(max_length=100)

foodbank/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views import generic
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import connection
from django.http import HttpResponseRedirect

from .models import Volunteer, FoodBank, Task, Volunteer_Task, Vehicle, TransitSchedule, FoodItem, \
    RecipientOrganization, DistributedFoodItem, Donator, FoodGroup

import re
import json
from datetime import datetime, timedelta
from collections import namedtuple

def staff_login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_staff:
            login(request, user)
            return redirect('foodbank:main_page')
        else:
            error_msg = 'Invalid credentials. Please try again.'
            return render(request, 'staff_login.html', {'error_msg': error_msg})
    return render(request, 'staff_login.html')

def staff_sign_up(request):
    username = request.POST.get("username")
    password = request.POST.get("password")
    first_name = request.POST.get("first_name")
    last_name = request.POST.get("last_name")
    email = request.POST.get("email")
    staff_key = request.POST.get("staff_key")

    if staff_key == "MakeMeStaff": # very primitive security lol
        user = User.objects.create_user(username, email=email, password=password)
        user.first_name = first_name
        user.last_name = last_name
        user.is_staff = True
        user.save()

        login(request, user)

        return redirect(reverse('foodbank:main_page'))
    else:
        error_msg = "Incorrect Staff Key."
        return redirect(reverse('foodbank:staff_login')+'?error_msg='+error_msg)

def home_view(request):
    error_msg = request.GET.get('error_msg')

    context = {
        'error_msg': error_msg
    }
    return render(request, 'home.html', context)

def login_view(request):
    username = request.POST.get("username")
    password = request.POST.get("password")

    user = authenticate(request, username=username, password=password)

    if user is not None:
        login(request, user)

        url = reverse('foodbank:main_page')
        response = HttpResponseRedirect(url)

        if not user.is_staff:
            vol = Volunteer.objects.filter(
                first_name=request.user.first_name, 
                last_name=request.user.last_name,
                email=user.email
                )[0]
        
            response.set_cookie('user_volunteer_id', json.dumps(vol.id))

        return response
    else:
        error_msg = 'Login Failed. Please enter username and password or create new account.'
        return redirect(reverse('foodbank:home')+'?error_msg='+error_msg)
    
def logout_view(request):
    logout(request)
    return redirect(reverse('foodbank:main_page'))

def sign_up_view(request):
    username = request.POST.get("username")
    password = request.POST.get("password")
    first_name = request.POST.get("first_name")
    last_name = request.POST.get("last_name")
    email = request.POST.get("email")

    if "phone_number" in request.POST:
        phone_number = request.POST.get("phone_number")
        street_address = request.POST.get("street_address")
        city = request.POST.get("city")
        home_state = request.POST.get("home_state")
        zip_code = request.POST.get("zip_code")

        vol = Volunteer.objects.create(
            first_name=first_name,
            last_name=last_name,
            street_address=street_address,
            city=city,
            home_state=home_state,
            zip_code=zip_code,
            phone_number=phone_number,
            email=email
        )

    user = User.objects.create_user(username, email=email, password=password)
    user.first_name = first_name
    user.last_name = last_name

    user.volunteer = vol
    user.save()

    login(request, user)

    url = reverse('foodbank:main_page')
    response = HttpResponseRedirect(url)
    response.set_cookie('user_volunteer_id', json.dumps(vol.id))
    return response

def main_page_view(request):
    if not request.user.is_authenticated:
        return redirect(reverse('foodbank:home'))

    msg = request.GET.get('msg')
    global dbSetupComplete
    return render(request, 'main_page.html', {'msg': msg, 'dbSetupComplete': dbSetupComplete, 'user': request.user})

# from Django documentation
def namedtuplefetchall(cursor):
    """
    Return all rows from a cursor as a namedtuple.
    Assume the column names are unique.
    """
    desc = cursor.description
    nt_result = namedtuple("Result", [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def execute_raw_sql(query, fetch=True):
    with connection.cursor() as cursor:
        cursor.execute(query)
        res = namedtuplefetchall(cursor) if fetch else None
    
    return res

def execute_many_raw_sql(queries):
    with connection.cursor() as cursor:
        for query in queries:
            cursor.execute(query)
    
    return

class VolunteerView(LoginRequiredMixin, generic.ListView):
    login_url = "/login/"
    redirect_field_name = ""
    model = Volunteer
    template_name='volunteer.html'
    context_object_name='volunteers'
    # phoneNumberRegex = re.compile("^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$")
    # emailRegex = re.compile("[^@]+@[^@]+\.[^@]+")

    def get_queryset(self):
        return Volunteer.objects.all()
    
    def get(self, req):
        error_msg = req.GET.get('error_msg') if 'error_msg' in req.GET else None
        volunteers = self.get_queryset()
        query = req.GET.get('q')
        if query:
            volunteers = volunteers.filter(
                Q(first_name__icontains=query) |
                Q(last_name__icontains=query) |
                Q(street_address__icontains=query) |
                Q(city__icontains=query) |
                Q(home_state__icontains=query) |
                Q(zip_code__icontains=query) |
                Q(phone_number__icontains=query) |
                Q(email__icontains=query)
            )

        # data summary queries
        # group volunteers by city
        res = execute_raw_sql("SELECT city, COUNT(id) AS NumVolunteers FROM foodbank_volunteer GROUP BY city;")

        context = {
            self.context_object_name: volunteers,
            'vol_count_by_city': res,
            'error_msg': error_msg,
        }

        return render(req, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        error_msgs = []

        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        street_address = request.POST.get('street_address')
        city = request.POST.get('city')
        home_state = request.POST.get('home_state')
        zip_code = request.POST.get('zip_code')
        phone_number = request.POST.get('phone_number')
        email = request.POST.get('email')

        # Check that at least one field is not empty
        if validateTextFields([first_name, last_name, street_address, city, home_state, zip_code, phone_number, email], error_msgs):            
            if 'add' in request.POST:
            
                Volunteer.objects.create(
                    first_name=first_name,
                    last_name=last_name,
                    street_address=street_address,
                    city=city,
                    home_state=home_state,
                    zip_code=zip_code,
                    phone_number=phone_number,
                    email=email
                )
            elif 'edit' in request.POST:
                volunteer_id = request.POST.get('volunteer_id')
                volunteer = Volunteer.objects.get(id=volunteer_id)

                for field in Volunteer._meta.get_fields():
                    name = field.name
                    if name != 'id' and name in request.POST and request.POST.get(name) != "":
                        newval = request.POST.get(name)
                        print(name, newval)
                        
                        volunteer.__setattr__(name, newval)
                
                volunteer.save()
            elif 'delete' in request.POST:
                volunteer_id = request.POST.get('volunteer_id')

                try:
                    Volunteer.objects.get(id=volunteer_id).delete()
                except Volunteer.DoesNotExist:
                    error_msg = 'Error when deleting Volunteer ' + str(volunteer_id) + ': volunteer does not exist'
                    return redirect(reverse("foodbank:volunteers")+'?error_msg='+error_msg)

        else:
            return redirect(reverse("foodbank:volunteers")+'?error_msg='+'\r\n'.join(error_msgs))



        return redirect(reverse("foodbank:volunteers"))


class FoodBankView(LoginRequiredMixin, generic.ListView):
    login_url = "/login/"
    redirect_field_name = ""
    model=FoodBank
    context_object_name='foodbanks'
    template_name='foodbank.html'

    def get_queryset(self):
        return FoodBank.objects.all()
    
    def get(self, req):
        error_msg = req.GET.get('error_msg') if 'error_msg' in req.GET else None
        foodbanks = self.get_queryset()
        potential_managers = Volunteer.objects.all()

        query = req.GET.get('q')
        if query:
            foodbanks = foodbanks.filter(
                Q(street_address__icontains=query) |
                Q(city__icontains=query) |
                Q(home_state__icontains=query) |
                Q(zip_code__icontains=query) |

foodbank/templates/admin_login.html
<!DOCTYPE html>
<html>
<head>
    <title>Admin Login</title>
    <!-- Include your CSS styles here -->
</head>
<body>
    <h1>Admin Login</h1>
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}

    <div class="form-container">
        <div class="form-box">
            <form method="post">
                {% csrf_token %}
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
                <button type="submit">Login</button>
            </form>
        </div>

        <div class="form-box">
            <h2>Create Admin User</h2>
            <form method="post" action="{% url 'foodbank:admin_sign_up' %}">
                {% csrf_token %}
                <label for="first_name">First Name:</label>
                <input type="text" id="first_name" name="first_name">
                <label for="last_name">Last Name:</label>
                <input type="text" id="last_name" name="last_name">
                <label for="email">Email:</label>
                <input type="text" id="email" name="email">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password">
                <label for="admin_key">Admin Key:</label>
                <input type="text" id="admin_key" name="admin_key">
                <button type="submit">Create Admin User</button>
            </form>
        </div>
    </div>
</body>
</html>

foodbank/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Foodbank Home</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&display=swap');

        body {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 150vh;
            margin: 0;
            font-family: 'Libre Baskerville', serif;
            background-color: #add8e6;
        }
        .header {
            font-size: 32px;
            margin-bottom: 20px;
            color: #1d3557;
            text-align: center;
        }
        .form-container {
            display: flex;
            justify-content: center;
            width: 80%;
        }
        .form-box {
            background-color: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
            margin: 0 10px;
            width: 300px;
            text-align: center;
            box-sizing: border-box;
        }
        .form-box label {
            margin: 5px 0;
            font-size: 14px;
            color: #333;
            display: block;
        }
        .form-box input {
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 14px;
            width: calc(100% - 16px);
            box-sizing: border-box;
        }
        .form-box button {
            margin: 10px 0;
            padding: 10px 20px;
            font-size: 14px;
            cursor: pointer;
            width: 100%;
            box-sizing: border-box;
            border: none;
            border-radius: 5px;
            background-color: #FFDBBB;
            color: darkorange;
            transition: background-color 0.3s ease, color 0.3s ease;
        }
        .form-box button:hover {
            background-color: #0056b3;
            color: white;
        }

        .header {
            padding-top: 5%;
        }
    </style>
</head>
<body>
<div class="header">Welcome to the Foodbank Home Page</div>
{% if error_msg %}
    <p style="color: red;">{{ error_msg }}</p>
{% endif %}

<div class="form-container">
    <div class="form-box">
        <h2>Login</h2>
        <form method="post" action="{% url 'foodbank:login' %}">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" id="user" name="username">
            <label for="password">Password:</label>
            <input type="password" id="pass" name="password">
            <button type="submit">Login</button>
        </form>
    </div>

    <div class="form-box">
        <h2>Sign Up</h2>
        <form method="post" action="{% url 'foodbank:sign_up' %}">
            {% csrf_token %}
            <label for="first_name">First Name:</label>
            <input type="text" id="first_name" name="first_name">
            <label for="last_name">Last Name:</label>
            <input type="text" id="last_name" name="last_name">
            <label for="email">Email:</label>
            <input type="text" id="email" name="email">
            <label for="phone_number">Phone Number:</label>
            <input type="text" id="phone_number" name="phone_number">
            <label for="street_address">Street Address:</label>
            <input type="text" id="street_address" name="street_address">
            <label for="city">City:</label>
            <input type="text" id="city" name="city">
            <label for="home_state">State:</label>
            <input type="text" id="home_state" name="home_state">
            <label for="zip_code">Zip Code:</label>
            <input type="text" id="zip_code" name="zip_code">
            <label for="username">Username:</label>
            <input type="text" id="username" name="username">
            <label for="password">Password:</label>
            <input type="password" id="password" name="password">
            <button type="submit">Sign Up</button>
        </form>
    </div>

    <div class="form-box">
    <h2>Staff Login</h2>
    <form method="get" action="{% url 'foodbank:staff_login' %}">
        <button type="submit">Staff Login</button>
    </form>
</div>

</div>
</body>
</html>

foodbank/templates/limited_main_page.html
<!DOCTYPE html>
<html>
<head>
    <title>Foodbank Main Page</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&display=swap');

        body {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            font-family: 'Libre Baskerville', serif;
            background-color: #add8e6;
        }
        .header {
            font-size: 36px;
            margin-bottom: 20px;
            color: #1d3557;
            text-align: center;
        }
        .subheader {
            font-size: 24px;
            margin-bottom: 20px;
            color: #ffffff;
            text-align: center;
        }
        .button-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            width: 80%;
        }
        .button-container button {
            margin: 10px;
            padding: 15px 30px;
            font-size: 16px;
            cursor: pointer;
            width: calc(33.33% - 20px);
            box-sizing: border-box;
            border: none;
            border-radius: 5px;
            background-color: #FFDBBB;
            color: darkorange;
            transition: background-color 0.3s ease;
        }
        .button-container button:hover {
            background-color: #0056b3;
            color: white;
        }

        .button-container .logout-button {
            background-color: darkorange;
            color: #FFDBBB;
            font-weight: bold;
            border: none;
        }
        .button-container .logout-button:hover {
            background-color: #0056b3;
            color: white;
            border: none;
        }

        a:link {
            text-decoration: none;
            color: darkorange;
        }
        a:visited {
            text-decoration: none;
            color: darkorange;
        }
        a:hover {
            text-decoration: none;
            color: darkorange;
        }
        a:active {
            text-decoration: none;
            color: darkorange;
        }

        /* Styles for messages */
        .messages {
            margin: 20px;
            padding: 10px;
            border-radius: 5px;
            background-color: #f8f8f8;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
        .messages .message {
            margin-bottom: 10px;
            padding: 10px;
            border-radius: 5px;
        }
        .messages .message.success {
            background-color: #d4edda;
            color: #155724;
        }
        .messages .message.error {
            background-color: #f8d7da;
            color: #721c24;
        }
    </style>
</head>
<body>
    <div class="header">Foodbank Management System</div>
    <div class="subheader">Welcome to the Foodbank Main Page</div>

    <!-- Display messages -->
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="message {{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}

    <div class="button-container">
        <button onclick="location.href='{% url 'foodbank:volunteer_tasks' %}'">Individual Shifts</button>
        <button onclick="location.href='{% url 'foodbank:transits' %}'">Transit Schedules</button>
        <button onclick="location.href='{% url 'foodbank:vol_add' %}'">Add Volunteer</button>
        <button onclick="location.href='{% url 'foodbank:task_add' %}'">Add Task</button>
        <button class="logout-button" onclick="location.href='{% url 'foodbank:logout' %}'">Logout</button>
    </div>
</body>
</html>

foodbank/templates/main_page.html
<!DOCTYPE html>
<html>
<head>
    <title>Foodbank Main Page</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&display=swap');

        body {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            font-family: 'Libre Baskerville', serif;
            background-color: #add8e6;
        }
        .header {
            font-size: 36px;
            margin-bottom: 20px;
            color: #1d3557;
            text-align: center;
        }
        .subheader {
            font-size: 24px;
            margin-bottom: 20px;
            color: #ffffff;
            text-align: center;
        }
        .button-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            width: 80%;
        }
        .button-container button {
            margin: 10px;
            padding: 15px 30px;
            font-size: 16px;
            font-weight: bold;
            cursor: pointer;
            width: calc(33.33% - 20px);
            box-sizing: border-box;
            border: none;
            border-radius: 5px;
            background-color: #FFDBBB;
            color: darkred;
            transition: background-color 0.3s ease;
        }
        .button-container button:hover {
            background-color: #0056b3;
            color: white;
        }

        .button-container .logout-button {
            background-color: darkorange;
            color: #FFDBBB;
            font-weight: bold;
            border: none;
        }
        .button-container .db-setup-button {
            background-color: darkorange;
            color: #FFDBBB;
            font-weight: bold;
            border: none;
        }
        .button-container .logout-button:hover {
            background-color: #0056b3;
            color: white;
            border: none;
        }

        a:link {
            text-decoration: none;
            color: darkorange;
        }
        a:visited {
            text-decoration: none;
            color: darkorange;
        }
        a:hover {
            text-decoration: none;
            color: darkorange;
        }
        a:active {
            text-decoration: none;
            color: darkorange;
        }

        button .disabled {
            background-color: darkgray;
            color: lightgrey;
        }
    </style>
</head>
<body>
<div class="header">Foodbank Management System</div>
<div class="subheader">Welcome to the Foodbank Main Page</div>
{% if msg %} <div class="subheader" style="color: green;">{{ msg }}</div> {% endif %}
<div class="button-container">
    <button onclick="location.href='{% url 'foodbank:volunteers' %}'" {% if user.is_staff == False %} disabled style="background-color: darkgray; color: lightgrey;" {% endif %}>Volunteer</button>
    <button onclick="location.href='{% url 'foodbank:vehicles' %}'">Vehicles</button>
    <button onclick="location.href='{% url 'foodbank:transits' %}'">Transit Schedules</button>
    <button onclick="location.href='{% url 'foodbank:volunteer_tasks' %}'">Individual Shifts</button>
    <button onclick="location.href='{% url 'foodbank:tasks' %}'">Tasks</button>
    <button onclick="location.href='{% url 'foodbank:foodbanks' %}'">Food Banks</button>
    <button onclick="location.href='{% url 'foodbank:fooditems' %}'">Food Items</button>
    <button onclick="location.href='{% url 'foodbank:foodgroups' %}'">Food Groups</button>
    <button onclick="location.href='{% url 'foodbank:donators' %}'" {% if user.is_staff == False %} disabled style="background-color: darkgray; color: lightgrey;" {% endif %}>Donators</button>
    <button onclick="location.href='{% url 'foodbank:distributed_food_items' %}'">Distributed Food Items</button>
    <button onclick="location.href='{% url 'foodbank:recipient_organizations' %}'" {% if user.is_staff == False %} disabled style="background-color: darkgray; color: lightgrey;" {% endif %}>Recipient Organizations</button>
    <button class="logout-button" onclick="location.href='{% url 'foodbank:logout' %}'">Logout</button>
    {% if dbSetupComplete == False %}<button class="db-setup-button" onclick="clicked(event)">Setup DB</button> {% endif %}
</div>
{% if user.is_staff == False %}
    <div class="small-message">Please ignore the greyed out buttons, they are for staff only.</div>
{% endif %}


</body>
<script>
    function clicked(e)
    {
        if(!confirm('This will fill the DB with sample entities. Only do this once, even amongst users and sessions! This is for testing purposes only. Select OK to continue.')) {
            e.preventDefault();
        } else {
            window.location.href = "{% url 'foodbank:setup_db' %}";
        }
    }
</script>
</html>